### ISSUE TITLE
When KVS pushes streaming data, an error of <Alignment trap: not handling> occurs, causing the process to crash.

### ISSUE THREAD

**Issue by Antong1997** [aws-samples/amazon-kinesis-video-streams-producer-embedded-c#72]
When we use the putKinesisVideoFrame interface to start the push of streaming data, after about 5s, an error of <Alignment trap: not handling instruction> will appear, causing the process to crash and a log will be attached.
The platform we use is RV1106 (ARMv7)
[kvs.log](https://github.com/aws-samples/amazon-kinesis-video-streams-producer-embedded-c/files/9745265/kvs.log)

**Comment by weichihl** [comment]
@Antong1997 The log `Alignment trap` is not from the embedded producer library. It would be helpful to provide the call stack when the app crashes.

**Comment by weichihl** [comment]
@Antong1997 I'll close this issue first since there are no updates. Please feel free to reopen it if there are some updates. Thanks.
