### ISSUE TITLE
IoT certificate fail cause aws services updated to tls1.2

### ISSUE THREAD

**Issue by overheat** [aws-samples/amazon-kinesis-video-streams-producer-embedded-c#77]
iot credential会报错，{"message":"Certificate is invalid on this endpoint"}

**Describe the bug**

**To Reproduce**
1. Use commit '....'
2. Compile with '....'
3. Run '....'

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - Arch: [e.g. ARM64]
 - OS: [e.g. Linux]

**Additional context**

**Comment by weichihl** [comment]
This issue should have been solved in commit [e5578f2](https://github.com/aws-samples/amazon-kinesis-video-streams-producer-embedded-c/commit/e5578f2ad7ba4f67a7f2a8ea7be82def49d8d595).
